### PR TITLE
Update Anaconda restrictions and usage notes

### PR DESCRIPTION
**Pull request by jbostian**

### CODE REVIEW

**Comment by zorts** [comment]
I agree with troy's comment. There is a lot of background on this in PYAN-881. Here's a comment I added that may be helpful:

This is a known issue in conda that cannot be fixed. See the 
[Conda User Guide: Troubleshooting: Shell commands open from the wrong location](https://conda.io/docs/user-guide/troubleshooting.html#shell-commands-open-from-the-wrong-location).

The problem is that bash only automatically invalidates its command hash table when it can "notice" that the table may be out-of-date, which essentially means whenever `$PATH` changes. `conda install` is a Python command; it puts new executables into a directory on `$PATH` but has no way to notify bash that the environment has changed.

There are two workarounds:

* Running `hash -r` will cause bash to discard the contents of the hash table.
* Running `source activate <env>` will essentially do the same.

**Comment by zorts** [comment]
Is it worth saying something about empty environments (as per PYAN-876)?

**Comment by jbostian** [comment]
In some of my own testing for a simplified environment with no nested bash, an empty environment always fails with a missing libpython shared library.  Always including Python when creating an environment avoids this pitfall, and is in line with some of the advice on StackOverflow about empty environments.  So I would agree with Jerry that we should include a restriction that addresses both PYAN-876 and PYAN-881.  Here is the text I'd like to include:

_When creating an "empty" conda environment, be sure to include the Python package.   Failing to do so can result in Python being unable to find its main shared library (libpython3.6m.so).  If you have an environment active and install a new package into it, please exit and re-enter the environment using source deactivate/activate to ensure that all path variables in the environment are set properly._

If we can agree to a restriction like this, I'll push up a new change.

**Comment by zorts** [comment]
sounds good to me.

**Comment by rharriszzz** [comment]
I think this is a problem with my changes to the activate script.


Sometime soon I will fix the activate script, so that the PATH and LIBPATH that it uses for its internal calls to python are always taken from the root environment.


________________________________

**Comment by tf3193** [comment]
Looks good, merging it

**Pull request merged**
